Add documentation + small code improvements in the git_hooks commit.

diff --git a/resources/hooks/vagrant/commit-msg b/resources/hooks/vagrant/commit-msg
--- a/resources/hooks/vagrant/commit-msg
+++ b/resources/hooks/vagrant/commit-msg
@@ -5,3 +5,12 @@ GIT_EMAIL=$(git config user.email)
 COMMIT_MSG_FILE=$1
 
 vagrant ssh --command "(exec $(HOOK_COMMAND)  '--git-user=$GIT_USER' '--git-email=$GIT_EMAIL' '$COMMIT_MSG_FILE')"
+
+# Validate exit code of above command
+RC=$?
+if [ "$RC" != 0 ]; then
+    exit $RC;
+fi
+
+# Clean exit:
+exit 0;
diff --git a/resources/hooks/vagrant/pre-commit b/resources/hooks/vagrant/pre-commit
--- a/resources/hooks/vagrant/pre-commit
+++ b/resources/hooks/vagrant/pre-commit
@@ -1,2 +1,12 @@
 #!/bin/sh
+
 vagrant ssh --command "(exec $(HOOK_COMMAND) '--skip-success-output')"
+
+# Validate exit code of above command
+RC=$?
+if [ "$RC" != 0 ]; then
+    exit $RC;
+fi
+
+# Clean exit:
+exit 0;
