Return the correct exit code

diff --git a/resources/hooks/pre-commit b/resources/hooks/pre-commit
--- a/resources/hooks/pre-commit
+++ b/resources/hooks/pre-commit
@@ -6,5 +6,11 @@
 #
 $(HOOK_COMMAND)
 
+# Validate exit code of above command
+RC=$?
+if [[ $RC != 0 ]]; then
+    exit $RC;
+fi
+
 # Clean exit:
 exit 0;
